name: CI Tests

on:
  push:
    paths:
      - 'web/src/**/*.spec-e2e.ts'
      - 'server/src/domain/**/*.spec.ts'
      - 'server/src/infra/http/**/*.spec-e2e.ts'
      - '**.json'
      - '**.yml'
    branches: [ main, development ]

jobs:
  setup-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'server'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.CI_SERVER_TEST_SECRETS}}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Up containers
        run: make up

      - name: Wait for Database container are up to run tests
        run: sleep 10

      - name: Run server unit tests
        run: make test-unit

      - name: Run server E2E tests
        run: make test-e2e

      - name: Change directory from server to web
        run: cd ../web

      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.CI_WEB_TEST_SECRETS}}" >> .env

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install firefox

      - name: List package.json content
        run: cat package.json

      - name: Run Next.js server in development mode
        run: npm run dev

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Down containers
        run: make down
