name: CI Tests

on:
  push:
    paths:
      - 'server/src/domain/**/*.spec.ts'
      - 'server/src/infra/http/**/*.spec-e2e.ts'
      - '**.json'
      - '**.yml'
    branches: [ main, development ]

jobs:
  setup-and-test:

    runs-on: ubuntu-latest
    container:
      image: node:22.16.0-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.CI_TEST_SECRETS}}" >> .env

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Up containers
        run: |
          make up

      - name: Wait for Database container are up to run tests
        run: |
          sleep 10

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run unit tests
        run: |
          make test-unit

      - name: Run E2E tests
        run: |
          make test-e2e

      - name: Down containers
        run: |
          make down
